version: '3.7'
services:
  app:
    container_name: styleguide_devtools
    build: ./
    command: sh -c "yarn run hmr-watch"
    ports:
      - 9000:9000
    volumes:
      - ../styleguide:/app/node_modules/styleguide
      - ./src:/app/src
      - ./config:/app/config
